project:
  # 项目包路径
  project-package: com.example.demo
  # 项目名称
  project-name: learn项目
  # 是否开启swagger
  enable-swagger: true
  # 项目描述
  description: 这是描述
  # 版本
  version: 1.0.1
  # 服务条款
  terms-of-service-url: http://www.baidu.com
  # 联系方式
  contact-name: pizazz
  contact-url: 18.179.14.91
  contact-email: pizazz777@gmail.com
  # 是否被其他服务器反向代理
  reverse-proxy-by-other-server: true

  auth:
    # 测试模式
    test-model: true
    # 管理员账号密码
    manager-name:
    manager-password:
    # 是否是后台管理系统
    background-manage-system: true
    # 登录方式
    login-type-enum-list:
      - account
      - email
      - mobile
    # 开启缓存
    caching-enabled: true
    # 开启授权缓存
    authorization-caching-enabled: true
    # 开启认证缓存
    authentication-caching-enabled: true
    # 系统中是否需要对手机号码进行验证
    check-mobile: true
  # json web token
  jwt:
    # JWT 接收方
    audience: admin
    # JWT 签发方
    issuer: admin
    # JWT 签名过期时间(毫秒)
    jwt-time-to-live: 3600000
  file:
    # 上传文件系统目录
    upload-file-dir: D:/resource/f
    # 上传文件访问地址前缀,使用nginx代理
    upload-file-url: Http://127.0.0.1:9090/f
  log:
    # 日志展示时是否获取用户信息
    show-user-info: true
    # 是否记录到数据库
    write-to-database: true
  cache:
    # 缓存key前缀
    prefix-cache-name: learn:sys:cache
  elasticsearch:
    # Elasticsearch index自动生成策略, true:存在先删除再重新设置, false:存在跳过
    es-index-schema-update: false
    # Elasticsearch需要扫描的注解包,用来在项目启动的时候根据类的注解生成index,analyzer等
    scan-package-list:
      - com.example.demo.entity
    skip: true
  office:
    # open office配置
    open-office:
      # 软件安装路径 windows和Linux不一样
      path: C:/Program Files (x86)/OpenOffice 4/
      # 启动端口 默认8100
      port: 8100
  video:
    # ffmpeg安装路径
    ffmpeg-path: D:/java/ffmpeg/bin/ffmpeg.exe
    # MEncoder安装路径
    m-encoder-path: D:/java/MPlayer-1.4
  minio:
    # 服务端访问地址
    end-point: http://192.168.2.134:9002
    # 访问账号
    access-key: admin123
    # 访问密码
    secret-key: admin123
    # 分区大小
    part-size: 104857600